### PR TITLE
Set-up react app

### PR DESCRIPTION
**Pull request by UbdaNam**
## What does this PR do?

This PR is raised to implement the following features: 👍 :

- [x] Create react app using CRA (`create-react-app`)
- [x] Use GitFlow to introduce new features 💡  
- [x] Setup linters 🐛 

## Description of the tasks completed 👇 

- [x] Set-up react app. 
- [x] Add bable to transpile modern JavaScript syntax into code that can run in all environments when writing React components
- [x] Use the linter tool that analyzes my source code to flag programming errors, bugs, stylistic errors, and suspicious constructs. 💯 
- [x] Check the accessibility of this project which means that websites, tools, and technologies are designed and developed so that people with disabilities ♿ can use them. For more information about Web accessibility [Click here](https://github.com/microverseinc/curriculum-html-css/blob/main/accessibility.md)☺️
     

  
## How should it be tested

Clone the repository
```
git clone https://github.com/UbdaNam/math-magicians.git
```
Navigate to the folder
```
cd math-magicians
```
Checkout the branch
```
git checkout Set-up-react-app
```
Run app
```
npm start
```

#### Thanks for reviewing my PR 😊

### CODE REVIEW

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Invalid Submission :red_circle:

invalid-submission

## Hey @UbdaNam :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements but I cannot proceed review of your pull request because there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

# Mandatory Changes ♻️

- [ ] It would be nice if you fix your linter errors because linters prevent you from making those errors which can break your app completely 👍
- [ ] Secondly, it would be great if you use microverse readme template in your repo to make your repo professional and descriptive 😊

**Comment by UbdaNam** [comment]
Hi @HAMMAS-SALEEM, thank you for reviewing some of the requirements of the project 😀. I will make the requested changes and I will submit re-review ♻️

**Review by julie-ify — APPROVED** [review]
Hi @UbdaNam,

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by UbdaNam** [comment]
Thank you @julie-ify for reviewing my PR 👍 and have a good day.

**Pull request merged**
